# Generated by Django 5.2 on 2025-04-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('university', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('edurank', models.TextField(blank=True)),
                ('department', models.TextField(blank=True)),
                ('publications', models.TextField(blank=True)),
                ('related', models.TextField(blank=True)),
                ('point_of_contact', models.TextField(blank=True)),
                ('scopes', models.TextField(blank=True)),
                ('research_abstract', models.TextField(blank=True)),
                ('lab_equipment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
    ]
