# Generated by Django 5.2 on 2025-04-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENABLE_OCR', models.BooleanField(default=True, help_text='Enable OCR processing for images and PDFs')),
                ('OCR_LANGUAGE', models.CharField(default='eng', help_text="Tesseract OCR language code (e.g., 'eng' for English, 'spa' for Spanish)", max_length=10)),
                ('REQUEST_TIMEOUT', models.IntegerField(default=15000, help_text='Request timeout in milliseconds')),
            ],
            options={
                'verbose_name': 'OCR Configuration',
                'verbose_name_plural': 'OCR Configurations',
            },
        ),
    ]
